packaging_format = 2

id = "hextris"
name = "Hextris"
description.en = "Fast paced puzzle game"
description.fr = "Jeu de puzzle très rapide"

version = "2023.06.08~ynh1"

maintainers = ["AerisOne"]

[upstream]
license = "GPL-3.0"
website = "http://hextris.github.io/"
demo = "https://hextris.io/"
code = "https://github.com/Hextris/Hextris"

[integration]
yunohost = ">= 11.1.20"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hextris"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Hextris/hextris/archive/8872ec47d694628e2fe668ebaa90b13d5626d95f.tar.gz"
        sha256 = "67f3fbd54c405717a25fb1e6f71d2b46e94c7ac6971861dd99ae5e58f6609892"
        autoupdate.upstream = "https://github.com/Hextris/hextris"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
