packaging_format = 2

id = "hextris"
name = "Hextris"
description.en = "Fast paced puzzle game"
description.fr = "Jeu de puzzle très rapide"

version = "2023.06.09~ynh1"

maintainers = ["AerisOne"]

[upstream]
license = "GPL-3.0"
website = "http://hextris.github.io/"
demo = "https://hextris.io/"
code = "https://github.com/Hextris/Hextris"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hextris"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Hextris/hextris/archive/3f4847dc8fd7dab3d1c87e6324b9159d92fbd396.tar.gz"
        sha256 = "38539c391cd97b1d90177c81b55a6194fd00e1b930bb21951d39b4902a4377ef"
        autoupdate.upstream = "https://github.com/Hextris/hextris"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
